name: vrabber-server

services:
  server:
    build:
      context: ../../.
      dockerfile: deploy/prod/app/Dockerfile
    networks:
      - vrabber
    restart: unless-stopped

networks:
  vrabber:
    external: true