services:
  server:
    build:
      context: ../
      dockerfile: ./deploy/app/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - vrabber
    restart: unless-stopped

networks:
  vrabber: