name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/vrabber/server
    steps:
      - name: checkout main
        run: git switch main
      - name: pull changes
        run: git pull
      - name: update containers
        run: docker compose -f ./deploy/docker-compose.yml up -d --build
